# Configurações para Netlify
[build]
  publish = "dist"
  command = "npm run build"

# Configurações de headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none'"

# Headers específicos para JavaScript
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Regras de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
