// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Modo offline/seguro para desenvolvimento: evita chamadas externas indesejadas
const DISABLE = (import.meta as any)?.env?.VITE_DISABLE_SUPABASE === 'true';
const supabaseUrl = (import.meta as any)?.env?.VITE_SUPABASE_URL as string | undefined;
const supabaseAnonKey = (import.meta as any)?.env?.VITE_SUPABASE_ANON_KEY as string | undefined;

// Stub mínimo compatível com a API usada no app quando Supabase estiver desabilitado
function createSupabaseStub() {
  const ok = {
    data: null,
    error: { message: 'Supabase disabled', status: 0, details: null, hint: null },
  } as any;
  const okNoError = { data: null, error: null } as any;
  const sub = { unsubscribe: () => {} };
  return {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: sub } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      signInWithPassword: async () => okNoError,
      signOut: async () => okNoError,
    },
    from: () => ({
      select: async () => ok,
      insert: async () => ok,
      upsert: async () => ok,
      update: async () => ok,
      delete: async () => ok,
      eq: () => ({ select: async () => ok, update: async () => ok, delete: async () => ok }),
    }),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

// Exporta cliente real somente quando configurado e habilitado
export const supabase =
  !DISABLE && supabaseUrl && supabaseAnonKey
    ? createClient<Database>(supabaseUrl, supabaseAnonKey, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : createSupabaseStub();
