// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = (import.meta as any)?.env?.VITE_SUPABASE_URL as string | undefined;
const supabaseAnonKey = (import.meta as any)?.env?.VITE_SUPABASE_ANON_KEY as string | undefined;

// Detecta ambiente de teste/CI para preferir stub e evitar acesso a localStorage/rede
const isTestEnv = (
  typeof process !== 'undefined' &&
  (process.env.VITEST || process.env.NODE_ENV === 'test')
) || (typeof (globalThis as any).vitest !== 'undefined');

// Stub mínimo compatível com a API usada no app quando Supabase estiver desabilitado
function createSupabaseStub() {
  const ok = {
    data: null,
    error: { message: 'Supabase disabled', status: 0, details: null, hint: null },
  } as any;
  const okNoError = { data: null, error: null } as any;
  const okUser = { data: { user: null }, error: null } as any;
  const sub = { unsubscribe: () => { } };
  return {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: sub } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => okUser,  // ✅ Adicionado método getUser faltante
      signInWithPassword: async () => okNoError,
      signOut: async () => okNoError,
    },
    from: () => ({
      select: () => ({
        eq: () => ({
          single: async () => ok,
          data: async () => ok,
        }),
        single: async () => ok,
        data: async () => ok,
      }),
      insert: async () => ok,
      upsert: async () => ok,
      update: () => ({
        eq: () => ({
          select: async () => ok,
          single: async () => ok,
        }),
      }),
      delete: () => ({
        eq: () => ({
          select: async () => ok,
          single: async () => ok,
        }),
      }),
      eq: () => ({
        select: () => ({
          single: async () => ok,
          data: async () => ok,
        }),
        update: async () => ok,
        delete: async () => ok,
        single: async () => ok,
      }),
      single: async () => ok,
    }),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

// Exporta cliente real sempre que as credenciais existirem (mesmo com DISABLE),
// e usamos o interceptor de fetch (em main.tsx) para bloquear chamadas em dev/offline.
export const supabase =
  supabaseUrl && supabaseAnonKey && !isTestEnv && typeof window !== 'undefined' && typeof localStorage !== 'undefined'
    ? createClient<Database>(supabaseUrl, supabaseAnonKey, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
    : createSupabaseStub();
