name: Deploy to Hostinger Root Domain (giselegalvao.com.br)

on:
  push:
    branches:
      - main # Ou a branch que você usa como principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deployment package
        run: |
          chmod +x ../scripts/deploy-prepare.sh
          ../scripts/deploy-prepare.sh

      - name: Deploy to Hostinger Root Domain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: \${{ secrets.FTP_SERVER }}
          username: \${{ secrets.FTP_USERNAME }}
          password: \${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
          dangerous-clean-slate: true # ⚠️ Cuidado: Isso apaga todos os arquivos do diretório de destino
