name: Deploy Hostinger - Configurações Corretas

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verificar arquivos build
        run: |
          echo "📁 Verificando arquivos no dist/:"
          ls -la dist/
          echo "📊 Tamanho do build:"
          du -sh dist/

      - name: Deploy para Hostinger (Configurações Corretas)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 147.93.39.155
          username: u116045488
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/u116045488/domains/giselegalvao.com.br/public_html/
          port: 21
          protocol: ftp
          timeout: 60000
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.log

      - name: Verificação pós-deploy
        run: |
          echo "✅ Deploy concluído com sucesso!"
          echo "🌐 Site disponível em: https://giselegalvao.com.br"
          echo "📱 Teste as páginas principais:"
          echo "   - https://giselegalvao.com.br/"
          echo "   - https://giselegalvao.com.br/resultado"
          echo "   - https://giselegalvao.com.br/quiz-descubra-seu-estilo"
