name: Deploy to Hostinger Root Domain (giselegalvao.com.br)

on:
  push:
    branches:
      - main # Ou a branch que você usa como principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run pre-deploy performance checks
        run: |
          chmod +x ./pre-deploy-performance-check.sh
          ./pre-deploy-performance-check.sh

      - name: Prepare deployment package
        run: |
          chmod +x ./scripts/deploy-prepare.sh
          ./scripts/deploy-prepare.sh

      - name: Deploy to Hostinger Root Domain (Tentativa 1 - IP Correto)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        continue-on-error: true
        id: deploy_ip
        with:
          server: 147.93.39.155
          username: u116045488
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/u116045488/domains/giselegalvao.com.br/public_html/
          port: 21
          protocol: ftp
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db

      - name: Deploy to Hostinger Root Domain (Tentativa 2 - Hostname)
        if: steps.deploy_ip.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        continue-on-error: true
        id: deploy_domain
        with:
          server: ftp.giselegalvao.com.br
          username: u116045488
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/u116045488/domains/giselegalvao.com.br/public_html/
          port: 21
          protocol: ftp
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db

      - name: Deploy to Hostinger Root Domain (Tentativa 3 - FTPS)
        if: steps.deploy_ip.outcome == 'failure' && steps.deploy_domain.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        continue-on-error: true
        id: deploy_ftps
        with:
          server: ftp.giselegalvao.com.br
          username: u116045488
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/u116045488/domains/giselegalvao.com.br/public_html/
          port: 21
          protocol: ftps
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db

      - name: Check deploy result
        run: |
          if [ "${{ steps.deploy_ip.outcome }}" == "success" ]; then
            echo "✅ Deploy realizado com sucesso via IP (147.93.39.155)"
          elif [ "${{ steps.deploy_domain.outcome }}" == "success" ]; then
            echo "✅ Deploy realizado com sucesso via hostname (ftp.giselegalvao.com.br)"
          elif [ "${{ steps.deploy_ftps.outcome }}" == "success" ]; then
            echo "✅ Deploy realizado com sucesso via FTPS"
          else
            echo "❌ Todas as tentativas de deploy falharam"
            echo "📋 Verifique:"
            echo "   - Se o secret FTP_PASSWORD está correto"
            echo "   - Se a conta FTP está ativa no painel Hostinger"
            echo "   - Se as configurações FTP estão corretas"
            exit 1
          fi

      - name: Post-deploy verification
        run: |
          echo "✅ Deploy concluído para giselegalvao.com.br"
          echo "🔗 Verificar: https://giselegalvao.com.br"
          echo "📊 Executar Lighthouse para verificar performance"
