name: Lovable Sync (Simplificado - Sem Token)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-lovable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Update local Lovable files
        run: |
          echo "Atualizando arquivos locais do Lovable..."
          npm run lovable:sync
          echo "✅ Sincronização local concluída"
          echo "ℹ️ Lovable Studio sincroniza automaticamente"
          echo "📱 Acesse: https://lovable.dev/@graciele"
